In [ ]:
import pandas as pd

base_credito = pd.read_csv("/content/risco-credito.csv", sep=',')
base_credito

FileNotFoundError: ignored

In [ ]:
x_risco_credito = base_credito.iloc[:,0:4].values
x_risco_credito

array([['ruim', 'alta', 'nenhuma', '0_15'],
       ['desconhecida', 'alta', 'nenhuma', '15_35'],
       ['desconhecida', 'baixa', 'nenhuma', '15_35'],
       ['desconhecida', 'baixa', 'nenhuma', 'acima_35'],
       ['desconhecida', 'baixa', 'nenhuma', 'acima_35'],
       ['desconhecida', 'baixa', 'adequada', 'acima_35'],
       ['ruim', 'baixa', 'nenhuma', '0_15'],
       ['ruim', 'baixa', 'adequada', 'acima_35'],
       ['boa', 'baixa', 'nenhuma', 'acima_35'],
       ['boa', 'alta', 'adequada', 'acima_35'],
       ['boa', 'alta', 'nenhuma', '0_15'],
       ['boa', 'alta', 'nenhuma', '15_35'],
       ['boa', 'alta', 'nenhuma', 'acima_35'],
       ['ruim', 'alta', 'nenhuma', '15_35']], dtype=object)

In [ ]:
y_risco_credito = base_credito.iloc[:,4].values
y_risco_credito

array(['alto', 'alto', 'moderado', 'alto', 'baixo', 'baixo', 'alto',
       'moderado', 'baixo', 'baixo', 'alto', 'moderado', 'baixo', 'alto'],
      dtype=object)

In [ ]:
from sklearn.preprocessing import LabelEncoder
label_encoder_lista = LabelEncoder()
label_encoder_divida = LabelEncoder()
label_encoder_garantia = LabelEncoder ()
label_encoder_renda = LabelEncoder()
label_encoder_risco = LabelEncoder()


In [ ]:
x_risco_credito[:,0] = label_encoder_historia.fit_transform(x_risco_credito[:,0])
x_risco_credito[:,1] = label_encoder_divida.fit_transform(x_risco_credito[:,1])
x_risco_credito[:,2] = label_encoder_garantia.fit_transform(x_risco_credito[:,2])
x_risco_credito[:,3] = label_encoder_renda.fit_transform(x_risco_credito[:,3])


NameError: ignored

In [ ]:
x_risco_credito

array([[2, 0, 1, 0],
       [1, 0, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 2],
       [1, 1, 1, 2],
       [1, 1, 0, 2],
       [2, 1, 1, 0],
       [2, 1, 0, 2],
       [0, 1, 1, 2],
       [0, 0, 0, 2],
       [0, 0, 1, 0],
       [0, 0, 1, 1],
       [0, 0, 1, 2],
       [2, 0, 1, 1]], dtype=object)

In [ ]:
y_risco_credito

array(['alto', 'alto', 'moderado', 'alto', 'baixo', 'baixo', 'alto',
       'moderado', 'baixo', 'baixo', 'alto', 'moderado', 'baixo', 'alto'],
      dtype=object)

In [ ]:
from sklearn.naive_bayes import GaussianNB

naive_risco_credito = GaussianNB()
naive_risco_credito.fit(x_risco_credito, y_risco_credito)

GaussianNB()

In [ ]:
previsao =naive_risco_credito.predict(x_risco_credito)
previsao

array(['alto', 'alto', 'alto', 'baixo', 'baixo', 'baixo', 'alto', 'baixo',
       'baixo', 'baixo', 'alto', 'alto', 'baixo', 'alto'], dtype='<U8')

In [79]:
import pandas as pd
import numpy as np

base_credito = pd.read_csv("/content/credit-data.csv", sep=',')
base_credito
base_credito.isnull().sum

<bound method NDFrame._add_numeric_operations.<locals>.sum of       clientid  income    age   loan  default
0        False   False  False  False    False
1        False   False  False  False    False
2        False   False  False  False    False
3        False   False  False  False    False
4        False   False  False  False    False
...        ...     ...    ...    ...      ...
1995     False   False  False  False    False
1996     False   False  False  False    False
1997     False   False  False  False    False
1998     False   False  False  False    False
1999     False   False  False  False    False

[2000 rows x 5 columns]>

In [93]:
filtro  = base_credito['age'] > 0

In [98]:
filtro

0       True
1       True
2       True
3       True
4       True
        ... 
1995    True
1996    True
1997    True
1998    True
1999    True
Name: age, Length: 2000, dtype: bool

In [97]:
idade_corrigida = base_credito[filtro]

In [96]:
idade_corrigida

clientid        income        age         loan  default
0            1  66155.925095  59.017015  8106.532131        0
1            2  34415.153966  48.117153  6564.745018        0
2            3  57317.170063  63.108049  8020.953296        0
3            4  42709.534201  45.751972  6103.642260        0
4            5  66952.688845  18.584336  8770.099235        1
...        ...           ...        ...          ...      ...
1995      1996  59221.044874  48.518179  1926.729397        0
1996      1997  69516.127573  23.162104  3503.176156        0
1997      1998  44311.449262  28.017167  5522.786693        1
1998      1999  43756.056605  63.971796  1622.722598        0
1999      2000  69436.579552  56.152617  7378.833599        0

[1997 rows x 5 columns]

In [84]:
import numpy

media = numpy.mean(idade_corrigida['age'])
media

-39.04620558489113

In [101]:
negativo= base_credito['age'] > 0
alterar = base_credito[negativo]
alterar

clientid        income        age         loan  default
0            1  66155.925095  59.017015  8106.532131        0
1            2  34415.153966  48.117153  6564.745018        0
2            3  57317.170063  63.108049  8020.953296        0
3            4  42709.534201  45.751972  6103.642260        0
4            5  66952.688845  18.584336  8770.099235        1
...        ...           ...        ...          ...      ...
1995      1996  59221.044874  48.518179  1926.729397        0
1996      1997  69516.127573  23.162104  3503.176156        0
1997      1998  44311.449262  28.017167  5522.786693        1
1998      1999  43756.056605  63.971796  1622.722598        0
1999      2000  69436.579552  56.152617  7378.833599        0

[1997 rows x 5 columns]

In [102]:
df = pd.DataFrame(alterar,columns=['age'] )




In [103]:
base_credito['age'][base_credito.age > 0].mean()


40.927688881035856

In [108]:
base_credito.loc[base_credito.age< 0,'age']= 40.92

In [109]:
previsores = base_credito.iloc[:,1:4].values
base_credito[base_credito.isna().any(axis=1)]



clientid        income  age         loan  default
28        29  59417.805406  NaN  2082.625938        0
30        31  48528.852796  NaN  6155.784670        0
31        32  23526.302555  NaN  2862.010139        0

In [90]:
classe = base_credito.iloc[:,4].values
classe

array([0, 0, 0, ..., 1, 0, 0])

In [112]:
# alterando os valores Nan pela média
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values = np.nan,strategy ='mean')
imputer = imputer.fit(previsores)
previsores = imputer.fit_transform(previsores)




In [115]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
previsores = scaler.fit_transform(previsores)
previsores [25:32]

array([[ 0.14801842,  0.        ,  0.30115562],
       [ 1.25363111,  0.        ,  1.69179347],
       [ 0.02763855,  0.        ,  0.63470486],
       [ 0.98348503,  0.        , -0.77570324],
       [ 0.94334509,  0.        ,  2.11085678],
       [ 0.22322905,  0.        ,  0.56210592],
       [-1.52242446,  0.        , -0.51971829]])

In [117]:
from sklearn.model_selection import train_test_split 

previsores_treinamento, previsores_teste, classe_treinamento, classe_teste = train_test_split(previsores, classe, test_size=0.25, random_state=0)

In [128]:
from sklearn.naive_bayes import GaussianNB
classificador  = GaussianNB()
classificador.fit(previsores_treinamento, classe_treinamento)
previsoes = classificador.predict(previsores_teste)


In [129]:
from sklearn.metrics import confusion_matrix, accuracy_score
precisao = accuracy_score(classe_teste, previsoes)
matriz = confusion_matrix(classe_teste, previsoes)

print(precisao)

print(pd.crosstab(classe_teste,previsoes))

0.87
col_0    0   1
row_0         
0      422  14
1       51  13
