In [3]:
import torch

lista = [[1,2,3],
         [4,5,6]]

tensor = torch.Tensor(lista)
print(tensor.dtype)
print (tensor)

tensor = torch.FloatTensor(lista)
print(tensor.dtype)
print (tensor)

tensor = torch.DoubleTensor(lista)
print(tensor.dtype)
print (tensor)

tensor = torch.LongTensor(lista)
print(tensor.dtype)
print (tensor)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


In [4]:
import numpy as np


arr = np.random.rand(3,4)
tns = torch.from_numpy(arr)
print(arr)
print(arr.dtype)
print(tns)
print(tns.dtype)

[[0.12324313 0.49550723 0.31202767 0.61049075]
 [0.31143008 0.57507292 0.47187019 0.23950215]
 [0.80972361 0.26016943 0.67154161 0.30408015]]
float64
tensor([[0.1232, 0.4955, 0.3120, 0.6105],
        [0.3114, 0.5751, 0.4719, 0.2395],
        [0.8097, 0.2602, 0.6715, 0.3041]], dtype=torch.float64)
torch.float64


In [6]:
tns1 = torch.ones(2,3)
tns0 = torch.zeros(4,5)
tnsr = torch.randn(3,3)

print(tns1)
print(tns0)
print(tnsr)

tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[-0.3258, -0.0300, -0.1541],
        [-1.3215, -0.2640,  1.4031],
        [-0.3477,  0.4990, -1.3213]])
