In [3]:
import torch

lista = [[1,2,3],
         [4,5,6]]

tensor = torch.Tensor(lista)
print(tensor.dtype)
print (tensor)

tensor = torch.FloatTensor(lista)
print(tensor.dtype)
print (tensor)

tensor = torch.DoubleTensor(lista)
print(tensor.dtype)
print (tensor)

tensor = torch.LongTensor(lista)
print(tensor.dtype)
print (tensor)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


In [4]:
 add import numpy as np


arr = np.random.rand(3,4)
tns = torch.from_numpy(arr)
print(arr)
print(arr.dtype)
print(tns)
print(tns.dtype)

[[0.04583734 0.41123995 0.04043862 0.57205924]
 [0.67599748 0.23686799 0.07285496 0.83517248]
 [0.07334084 0.1391744  0.78143816 0.08457977]]
float64
tensor([[0.0458, 0.4112, 0.0404, 0.5721],
        [0.6760, 0.2369, 0.0729, 0.8352],
        [0.0733, 0.1392, 0.7814, 0.0846]], dtype=torch.float64)
torch.float64
