In [184]:
import torch

lista = [[1,2,3],
         [4,5,6]]

tensor = torch.Tensor(lista)
print(tensor.dtype)
print (tensor)

tensor = torch.FloatTensor(lista)
print(tensor.dtype)
print (tensor)

tensor = torch.DoubleTensor(lista)
print(tensor.dtype)
print (tensor)

tensor = torch.LongTensor(lista)
print(tensor.dtype)
print (tensor)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


In [185]:
import numpy as np


arr = np.random.rand(3,4)
tns = torch.from_numpy(arr)
print(arr)
print(arr.dtype)
print(tns)
print(tns.dtype)

[[0.52866845 0.20565701 0.55459637 0.17441963]
 [0.93254457 0.13502775 0.6870469  0.81158833]
 [0.26953288 0.4296193  0.22428246 0.6874911 ]]
float64
tensor([[0.5287, 0.2057, 0.5546, 0.1744],
        [0.9325, 0.1350, 0.6870, 0.8116],
        [0.2695, 0.4296, 0.2243, 0.6875]], dtype=torch.float64)
torch.float64


In [186]:
tns1 = torch.ones(2,3)
tns0 = torch.zeros(4,5)
tnsr = torch.randn(3,3)

print(tns1)
print(tns0)
print(tnsr)


tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[ 0.3996, -0.9074, -0.5744],
        [ 0.6948, -1.1040, -0.8097],
        [-1.1103,  0.9318,  0.6147]])


In [187]:
# Tensor para array numpy

arr= tnsr.data.numpy()
print (arr)

[[ 0.39964616 -0.9074388  -0.57438624]
 [ 0.69477415 -1.1040308  -0.8097354 ]
 [-1.1103017   0.9317609   0.6146655 ]]


In [188]:
print (tnsr,'\n')
# contagem de linhas
tnsr[1,2]= -10

print(tnsr,'\n')
# contagem de linhas/colunas
print(tnsr[1:3])

# buscar único elemento

print(tnsr[0,2])

tensor([[ 0.3996, -0.9074, -0.5744],
        [ 0.6948, -1.1040, -0.8097],
        [-1.1103,  0.9318,  0.6147]]) 

tensor([[  0.3996,  -0.9074,  -0.5744],
        [  0.6948,  -1.1040, -10.0000],
        [ -1.1103,   0.9318,   0.6147]]) 

tensor([[  0.6948,  -1.1040, -10.0000],
        [ -1.1103,   0.9318,   0.6147]])
tensor(-0.5744)


In [189]:
tns = tnsr[0:2,:]
#Consultar dimensoes através do shape
print(tns.shape)
print(tns1.shape,'\n')

#verificando valores
print(tns)
print(tns1,'\n')

print(tns+tns1,'\n')

# multiplicação de matrizes (Produto Interno)

print(torch.mm(tns1,tns.T))

torch.Size([2, 3])
torch.Size([2, 3]) 

tensor([[  0.3996,  -0.9074,  -0.5744],
        [  0.6948,  -1.1040, -10.0000]])
tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

tensor([[ 1.3996,  0.0926,  0.4256],
        [ 1.6948, -0.1040, -9.0000]]) 

tensor([[ -1.0822, -10.4093],
        [ -1.0822, -10.4093]])
