In [197]:
import torch

lista = [[1,2,3],
         [4,5,6]]

tensor = torch.Tensor(lista)
print(tensor.dtype)
print (tensor)

tensor = torch.FloatTensor(lista)
print(tensor.dtype)
print (tensor)

tensor = torch.DoubleTensor(lista)
print(tensor.dtype)
print (tensor)

tensor = torch.LongTensor(lista)
print(tensor.dtype)
print (tensor)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


In [198]:
import numpy as np


arr = np.random.rand(3,4)
tns = torch.from_numpy(arr)
print(arr)
print(arr.dtype)
print(tns)
print(tns.dtype)

[[0.59569595 0.69265086 0.69552088 0.61404324]
 [0.91853664 0.75766493 0.11736567 0.97184527]
 [0.80449526 0.047281   0.94683493 0.39550287]]
float64
tensor([[0.5957, 0.6927, 0.6955, 0.6140],
        [0.9185, 0.7577, 0.1174, 0.9718],
        [0.8045, 0.0473, 0.9468, 0.3955]], dtype=torch.float64)
torch.float64


In [199]:
tns1 = torch.ones(2,3)
tns0 = torch.zeros(4,5)
tnsr = torch.randn(3,3)

print(tns1)
print(tns0)
print(tnsr)


tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[ 0.1516,  1.3163,  0.3786],
        [ 0.3894,  0.0117, -0.0322],
        [-0.4052, -0.5146,  0.3377]])


In [200]:
# Tensor para array numpy

arr= tnsr.data.numpy()
print (arr)

[[ 0.15159723  1.3162584   0.37858558]
 [ 0.38938278  0.01168246 -0.03215717]
 [-0.4051939  -0.5145935   0.33771154]]


In [201]:
print (tnsr,'\n')
# contagem de linhas
tnsr[1,2]= -10

print(tnsr,'\n')
# contagem de linhas/colunas
print(tnsr[1:3])

# buscar único elemento

print(tnsr[0,2])

tensor([[ 0.1516,  1.3163,  0.3786],
        [ 0.3894,  0.0117, -0.0322],
        [-0.4052, -0.5146,  0.3377]]) 

tensor([[  0.1516,   1.3163,   0.3786],
        [  0.3894,   0.0117, -10.0000],
        [ -0.4052,  -0.5146,   0.3377]]) 

tensor([[  0.3894,   0.0117, -10.0000],
        [ -0.4052,  -0.5146,   0.3377]])
tensor(0.3786)


In [202]:
tns = tnsr[0:2,:]
#Consultar dimensoes através do shape
print(tns.shape)
print(tns1.shape,'\n')

#verificando valores
print(tns)
print(tns1,'\n')

print(tns+tns1,'\n')

# multiplicação de matrizes (Produto Interno)

print(torch.mm(tns1,tns.T))

torch.Size([2, 3])
torch.Size([2, 3]) 

tensor([[  0.1516,   1.3163,   0.3786],
        [  0.3894,   0.0117, -10.0000]])
tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

tensor([[ 1.1516,  2.3163,  1.3786],
        [ 1.3894,  1.0117, -9.0000]]) 

tensor([[ 1.8464, -9.5989],
        [ 1.8464, -9.5989]])


In [205]:
#achatamento das dimensões

tns= torch.randn(2,2,3)
print(tns,'\n')

print (tns.size(),'\n')

tns = tns.view(tns.size(0), -1)
print (tns)


tensor([[[-0.4083, -0.7810,  0.2505],
         [-0.3859,  1.7827, -0.4887]],

        [[-2.2226, -0.4203, -0.8046],
         [ 0.4125, -0.9118,  0.7292]]]) 

torch.Size([2, 2, 3]) 

tensor([[-0.4083, -0.7810,  0.2505, -0.3859,  1.7827, -0.4887],
        [-2.2226, -0.4203, -0.8046,  0.4125, -0.9118,  0.7292]])
