In [272]:
import torch

lista = [[1,2,3],
         [4,5,6]]

tensor = torch.Tensor(lista)
print(tensor.dtype)
print (tensor)

tensor = torch.FloatTensor(lista)
print(tensor.dtype)
print (tensor)

tensor = torch.DoubleTensor(lista)
print(tensor.dtype)
print (tensor)

tensor = torch.LongTensor(lista)
print(tensor.dtype)
print (tensor)

torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float32
tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.float64
tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.int64
tensor([[1, 2, 3],
        [4, 5, 6]])


In [273]:
import numpy as np


arr = np.random.rand(3,4)
tns = torch.from_numpy(arr)
print(arr)
print(arr.dtype)
print(tns)
print(tns.dtype)

[[0.8910989  0.08611907 0.59880919 0.99380896]
 [0.15043112 0.39039783 0.43502075 0.53226844]
 [0.38005692 0.69393742 0.88158421 0.74953358]]
float64
tensor([[0.8911, 0.0861, 0.5988, 0.9938],
        [0.1504, 0.3904, 0.4350, 0.5323],
        [0.3801, 0.6939, 0.8816, 0.7495]], dtype=torch.float64)
torch.float64


In [274]:
tns1 = torch.ones(2,3)
tns0 = torch.zeros(4,5)
tnsr = torch.randn(3,3)

print(tns1)
print(tns0)
print(tnsr)


tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])
tensor([[ 0.2594, -0.7803,  0.2555],
        [-0.6198, -2.1472,  1.8741],
        [ 0.1568, -0.4720,  0.4224]])


In [275]:
# Tensor para array numpy

arr= tnsr.data.numpy()
print (arr)

[[ 0.2594368  -0.7802585   0.25552714]
 [-0.6198432  -2.1471741   1.8740572 ]
 [ 0.15684335 -0.47197786  0.42235997]]


In [276]:
print (tnsr,'\n')
# contagem de linhas
tnsr[1,2]= -10

print(tnsr,'\n')
# contagem de linhas/colunas
print(tnsr[1:3])

# buscar único elemento

print(tnsr[0,2])

tensor([[ 0.2594, -0.7803,  0.2555],
        [-0.6198, -2.1472,  1.8741],
        [ 0.1568, -0.4720,  0.4224]]) 

tensor([[  0.2594,  -0.7803,   0.2555],
        [ -0.6198,  -2.1472, -10.0000],
        [  0.1568,  -0.4720,   0.4224]]) 

tensor([[ -0.6198,  -2.1472, -10.0000],
        [  0.1568,  -0.4720,   0.4224]])
tensor(0.2555)


In [277]:
tns = tnsr[0:2,:]
#Consultar dimensoes através do shape
print(tns.shape)
print(tns1.shape,'\n')

#verificando valores
print(tns)
print(tns1,'\n')

print(tns+tns1,'\n')

# multiplicação de matrizes (Produto Interno)

print(torch.mm(tns1,tns.T))

torch.Size([2, 3])
torch.Size([2, 3]) 

tensor([[  0.2594,  -0.7803,   0.2555],
        [ -0.6198,  -2.1472, -10.0000]])
tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

tensor([[ 1.2594,  0.2197,  1.2555],
        [ 0.3802, -1.1472, -9.0000]]) 

tensor([[ -0.2653, -12.7670],
        [ -0.2653, -12.7670]])


In [278]:
#achatamento das dimensões

tns= torch.randn(2,2,3)
print(tns,'\n')

print (tns.size(),'\n')

tns = tns.view(tns.size(0), -1)
print (tns)


tensor([[[ 0.6859, -0.3431,  1.9589],
         [ 0.1078, -0.3114, -0.5627]],

        [[ 1.6840,  0.0720, -1.0129],
         [ 0.4731,  0.1749, -0.2145]]]) 

torch.Size([2, 2, 3]) 

tensor([[ 0.6859, -0.3431,  1.9589,  0.1078, -0.3114, -0.5627],
        [ 1.6840,  0.0720, -1.0129,  0.4731,  0.1749, -0.2145]])


In [279]:
# Verificando a disponibilidade da GPU


if torch.cuda.is_available():
    device = torch.device('cuda - GPU')
else:
    device =torch.device('cpu')
print('device :',device)


tnsr = tnsr.to(device)
print(tnsr)

device : cpu
tensor([[  0.2594,  -0.7803,   0.2555],
        [ -0.6198,  -2.1472, -10.0000],
        [  0.1568,  -0.4720,   0.4224]])
